### ISSUE TITLE
oradb module using deprecated functions causing warnings in puppet console

### ISSUE THREAD

**Issue by daveseff** [biemond/biemond-oradb#101]
using this module cause puppet to throw the following warnings:

Warning: Creating db_directory_structure via Puppet.newtype is deprecated and will be removed in a future release. Use Puppet::Type.newtype instead.

**Comment by biemond** [comment]
Thanks for reporting this.

I will fix it or you can send me a pull request. basically I need to replace in the types located  in lib/puppet/type
