### ISSUE TITLE
oracle_exists logic is incorrect

### ISSUE THREAD

**Issue by vchepkov** [biemond/biemond-oradb#105]
I don't think this code works they way you think it is:

>  # check if the oracle software already exists
>  $found = oracle_exists( $oracle_home )

Custom functions are executed on master, not on the node
https://docs.puppet.com/guides/custom_functions.html

**Comment by biemond** [comment]
Hi,

you are correct but it should work because I generate facts before puppet runs, passed on to apply or master and this custom function only reads if the facts are there

Thanks
