### ISSUE TITLE
duplicate initParam in dbtemplate_12.1.dbt.erb

### ISSUE THREAD

**Issue by Mortinke** [biemond/biemond-oradb#126]
Currently, there are two different static values for the audit_trail parameter in the dbtemplate_12.1.dbt.erb template. We should remove one of this and make the other one dynamic.

Current state:
```
         <initParam name="audit_trail" value="none"/>
        ......
         <initParam name="audit_trail" value="db"/>
```

Desired state:
```
         <initParam name="audit_trail" value="<%= @audit_trail %>"/>
```

**Comment by biemond** [comment]
thanks,

I will remove one ( what is a good default value?), I don't know about an audit parameter. DB rsp file doesn't have this param so it only used by dbt templates.

**Comment by Mortinke** [comment]
Yes, the _audit_trial_ paramater is a database only parameter und exists only in the database configuration file. 

This are the possible values: { none | os | db [, extended] | xml [, extended] }.
I prefer the value "db", but any other value depending on the auditing needs. 
Everybody could find the oracle recommendations for this value in this presentation [Upgrade_12c](http://apex.oracle.com/pls/apex/f?p=202202:2:::::P2_SUCHWORT:migrate12c). 

I think we should use the "none" as default value, so by default a small database is created.
