### ISSUE TITLE
add new database_type SE2

### ISSUE THREAD

**Issue by Mortinke** [biemond/biemond-oradb#127]
With Oracle 12.1.0.2 the license modules SE (standard edition) and SEONE (standard edition on) were replaced with SE2 (standard edition two). We can only install Oracle 12.1.0.2 with EE or SE2. 

Could we add the new database_type SE2 and change the verification?

```
  if ( $version in ['11.2.0.1','11.2.0.3','11.2.0.4','12.1.0.1'] and !($database_type in ['EE','SE','SEONE'])) {
    fail('Unrecognized database type, please use EE|SE|SEONE')
  } elsif ( $version in ['12.1.0.2'] and !($database_type in ['EE','SE2'])) {
    fail('Unrecognized database type, please use EE|SE2')    
  }
```

**Comment by biemond** [comment]
Thanks , I will change it
