### ISSUE TITLE
Error installing 2 OracleDB on the same server

### ISSUE THREAD

**Issue by fduranti** [biemond/biemond-oradb#128]
It's possible that I'm doing something wrong somewhere but it seems not possible to install 2 OracleDB of the same version (probably it's possible with 2 different version) on the same server.
I need to install them because of our SAP servers that sometimes have more than one DB installed and each of them has it's own oracle home and environment.

When I try to install 2 database i get this error because oradb is trying to call 2 time the same db_directory_structure with the same name.

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Db_directory_structure[oracle structure 12.1.0.2] is already declared in file /etc/puppetlabs/code/environments/development/modules/oradb/manifests/installdb.pp:90; cannot redeclare at /etc/puppetlabs/code/environments/development/modules/oradb/manifests/installdb.pp:90 at /etc/puppetlabs/code/environments/development/modules/oradb/manifests/installdb.pp:90:3 at /etc/puppetlabs/code/environments/development/site/profile/manifests/oracle/install.pp:19 on node itnaptpupl01.q8int.com

This is the code I'm using to test:

```

  oradb::installdb{ 'home1':
     version           => '12.1.0.2',
     file              => 'linuxamd64_12c_database',
     database_type     => 'EE',
     ora_inventory_dir => '/oracle/orainv',
     oracle_base       => '/oracle',
     oracle_home       => '/oracle/product/12.1/db1',
     bash_profile      => false,
     user              => 'oracle',
     group             => 'oinstall',
     group_install     => 'oinstall',
     group_oper        => 'oper',
     download_dir      => '/opt/installer/oracle',
     zip_extract       => false,
  }
    oradb::installdb{ 'home2':
     version           => '12.1.0.2',
     file              => 'linuxamd64_12c_database',
     database_type     => 'EE',
     ora_inventory_dir => '/oracle/orainv',
     oracle_base       => '/oracle',
     oracle_home       => '/oracle/product/12.1/db2',
     bash_profile      => false,
     user              => 'oracle',
     group             => 'oinstall',
     group_install     => 'oinstall',
     group_oper        => 'oper',
     download_dir      => '/opt/installer/oracle',
     zip_extract       => false,
  }


```

Any workaround or is this planned for future release?
I'll try to check the module myself in the afternoon to see if there's some simple change to make it work.

**Comment by biemond** [comment]
interesting 

mostly nowadays we have 1 vm for 1 oracle install or at least different db version. So I didn't test that combination.

probably the fix for this is easy 
https://github.com/biemond/biemond-oradb/blob/master/manifests/installdb.pp#L91

maybe we need to add the title to this name.
but it can fail on other code because it is the same version and should do more with title.

thanks

**Comment by fduranti** [comment]
Normally we do the same but some of our installation of SAP need different instance/oracle installation on the same server.

I'm doing some tests just now to see if it works using title and it seems i need to use it in more than just the db_directory_structure (prabably also rsp file created should be different and so on). At the end of the test I'll try to do a pull request with the changes.

**Comment by biemond** [comment]
👍
