### ISSUE TITLE
db_install_${version}.rsp - why this file needs to be in the ${download_dir}

### ISSUE THREAD

**Issue by wiseproton** [biemond/biemond-oradb#131]
New to puppet, please bear with my ignorance.

I am trying to figure out why the db_install_${version}.rsp needs to be in the ${download_dir}.
This is my problem - couldn't figure out a good solution;
All of my database software is unzipped and shared across all VMs using NFS read only mounts.
If I tried to use this shared software location (zip_extract=>false), I get the following error -

Error: Could not set 'present' on ensure: Read-only file system @ dir_s_mkdir - /mnt/oraclesoftware/db_install_11.2.0.4.rsp20160911-12575-9n36cs.lock at 168:/etc/puppetlabs/code/environments/production/modules/oradb/manifests/installdb.pp

According to line 168 in installdb.pp - it is trying to ensure that it is present.

```
if ! defined(File["${download_dir}/db_install_${version}.rsp"]) {
  file { "${download_dir}/db_install_${version}.rsp":
    ensure  => present,
```

What is the technical reasons that this response file be in the same download directory?
BTW - I am able to successfully install using the zip_extract=true option which adds about 2 additional minutes in local copying the zip files and extracting them.

Thank you.

**Comment by biemond** [comment]
Hi

it is  just a response file ( just 1 time for a particular VM )
but I understand your issue.  Let's see how we can fix it without making it too complicated or adding more parameters

Thanks Edwin

**Comment by wiseproton** [comment]
Thank you. Appreciate your time and effort.
