### ISSUE TITLE
remove unused parameter $grid_product_home_dir in db_control

### ISSUE THREAD

**Issue by Mortinke** [biemond/biemond-oradb#138]
There are _:grid_product_home_dir_ parameter in db_control, which is not used in base.rb, srvctl.rb and sqlplus.rb.
Could we remove this parameter? 
All commands are already executed in #{oracle_home}, which (is | should) depending on the instance type $ORACLE_HOME or $GRID_HOME.

If the _grid_product_home_dir_ parameter is removed, we can also remove the _grid_home_ parameter in dbactions.pp, which only exists because the _grid_product_home_dir_ parameter.

**Comment by biemond** [comment]
yeah,

let's do that. less to maintain and no confusion about these parameters
