### ISSUE TITLE
Add ability to control database with srvctl in dbactions.pp

### ISSUE THREAD

**Issue by Mortinke** [biemond/biemond-oradb#140]
Currently, the default value "sqlplus" is always used for the _provider_ parameter for _db_control.rb_, if the _db_type_ is "database". This works great with single instances but not for multiple instances in a RAC. 
Here we should add the ability to use the recommended method _srvctl_ to control database instance in a RAC.

**Comment by biemond** [comment]
ok, good fix

but I don't have any RAC instances or any knowledge about this, so I need you to test the RAC part.

**Comment by Mortinke** [comment]
To continue to support the mount status with database instance, we must modify or expand the command in _srvctl.rb_ like in _sqlplus.rb_.
Unfortunately, my ruby skills are low, so I think that I need support here.

If we want to start the database in mount status, we musst execute the following command
```
srvctl "#{action} database -db #{name} -o mount" 
```
So, the srvctl command is only expanded with "-o mount".

I  look forward to any support.

**Comment by biemond** [comment]
Hi

something like this

is there also something to know the current status of the DB. If you want to go from mount to start or from start to mount.

```
Puppet::Type.type(:db_control).provide(:srvctl, :parent => :base) do


  def instance_control(action)
    name        = resource[:instance_name]
    Puppet.debug "instance action: #{action} on instance type #{resource[:db_type]}"
    force = (action == :stop) ? '-f' : ''
    mount = (action == :mount) ? '-o mount' : ''

    @output = case resource[:db_type]
    when :database
      srvctl "#{action} database -db #{name} #{mount}"
    when :asm
      srvctl "#{action} asm #{force}"
    else
      fail "internal error unknown action #{action}"
    end
    if unsuccessful?
      fail @output
    else
      Puppet.debug @output if @output
    end
  end

```
