### ISSUE TITLE
Could not autoload puppet/type/db_control

### ISSUE THREAD

**Issue by mal1410** [biemond/biemond-oradb#144]
During a Puppet Agent run, the catalog can sometimes not be retrieved from server due to a problem to autoload some types. 

**here is the log**:
Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/db_control: Could not autoload puppet/provider/db_control/sqlplus: Could not find parent provider base of sqlplus at /etc/puppetlabs/code/environments/staging/modules/prof_oradb/manifests/oradb_creation.pp:165:3 on node sta-73.afis-staging.local

**This occurs also using biemond/orawls** module but then I obtain:
Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/yaml_setting: Could not autoload puppet/provider/yaml_setting/mapped: no such file to load -- puppetx/filemapper at /etc/puppetlabs/code/environments/test/modules/orawls/manifests/domain.pp:642:5 at /etc/puppetlabs/code/environments/test/modules/prof_weblogic/manifests/create_weblogic_domain.pp:20 on node test-14.afis-test.local

The issue occurs randomly, running again the agent solves it temporarily. 
Puppet agent version is 4.5.2

Here is the **code causing the issue**:

> db_control{"${database_name} restart":
> ensure => 'running', #running|start|abort|stop
> instance_name => $database_name,
> oracle_product_home_dir => $prof_oradb::oradb_constants::oracle_home_dir,
> os_user => $prof_oradb::os_constants::oracle_os_user,
> refreshonly => true,
> subscribe => [Ora_init_param["${init_param_open_cursors}@${database_name}"],
> Ora_init_param["${init_param_processes}@${database_name}"],
> Ora_init_param["${init_param_job_queue_processes}@${database_name}"],
> Ora_init_param["${init_param_session_cached_cursors}@${database_name}"],
> Ora_init_param["${init_param_db_securefile}@${database_name}"],
> Ora_init_param["${init_param_sga_target}@${database_name}"],
> Ora_init_param["${init_param_shared_pool_size}@${database_name}"],
> Ora_init_param["${init_param_pga_aggregate_target}@${database_name}"],
> Ora_init_param["${init_param_memory_target}@${database_name}"],],
> }
>

**Comment by biemond** [comment]
Interesting and probably hard to find the real issue, it looks like some ruby loading problem.

Did you also got this issue with previous puppet agents, it also can be a ruby issue.

Thanks

**Comment by mal1410** [comment]
I haven't tried with previous agent versions.
But I tried with: 
        biemond-orawls 1.0.53 and 1.0.56 
        biemond-oradb 2.0.6 and 2.0.7

and had same issue

**Comment by mal1410** [comment]
BTW, this is the answer I received from Puppet team:

Thanks for contacting us with your support issue. This sounds like possible misconfiguration of the modules in question, most likely affecting their custom providers. This is a pretty rare error, and I understand it tends to pop up with misconfigured plugins (such as the provider in question here). Since these are unsupported third-party modules, the best advice we could give is to make sure you have pluginsync properly enabled and if that doesn't get the providers properly synced, you may need to open up issues with the creators of those modules through their respective GitHub pages.

**Comment by biemond** [comment]
Ok, do you have it very regularly or sometimes.
and are you using a puppet master if so can you try some puppet apply runs

Yeah with every module update I make sure the puppet master is restarted, do some dummy runs on the master ( plus add modules on primary , 1st location)  and then go for the puppet agent run

**Comment by mal1410** [comment]
I use a puppet master (V2016.2.0)
I have the problem quite often. I think I have it systematically on a fresh node (brand new installed VM)

I'll give a try to puppet apply  runs

**Comment by biemond** [comment]
thanks, plugin sync can be very tricky

when we have the same problem with puppet apply, I can at least easily reproduce it else it is probably some puppet master/sync issue.

**Comment by mal1410** [comment]
Hi,

I tried the puppet apply, but was not able to reproduce the problem that way.
Looks more as a master/sync issue.

**Comment by biemond** [comment]
indeed, 

master and agent used to have the same codebase but I think they moved to clojure for performance  reasons, I guess it must be some sync catalog issue.  I am not doing things what will not work on a puppet master ( using facts etc which can also be used on master ) . 
Sometimes it goes wrong so it can be something what can influence this behaviour, maybe a timing , concurrency or load issue.
