### ISSUE TITLE
dbca support for vaiables

### ISSUE THREAD

**Issue by johmicd** [biemond/biemond-oradb#148]
It would be nice to support variables with template 

-variables disk01=/u01/oradata/,disk02=/u02/oradata/,disk03=/u03/oradata/,disk04=/u04/oradata/

you could also use this to replace your process of string replace you currently do for template

**Comment by johmicd** [comment]
example of use it in the template 

         <member ordinal="0" memberName="redo11.log" filepath="{disk01}/{DB_UNIQUE_NAME}/"/>
         <member ordinal="1" memberName="redo13.log" filepath="{disk03}/{DB_UNIQUE_NAME}/"/>

**Comment by biemond** [comment]
That's nice. 

you mean on your own dbt template.
are you now using a dbt template on different servers with different disk layout.

**Comment by johmicd** [comment]
correct

**Comment by biemond** [comment]
Done, I added to the latest release

Thanks

**Comment by johmicd** [comment]
o cool thanks!
