### ISSUE TITLE
oradb_client 11.2.0.4 install error with PROXY_REALM

### ISSUE THREAD

**Issue by surcouf** [biemond/biemond-oradb#152]
Hi, 

 Oracle 11.2.0.4 client installation doesn't work and return error message about PROXY_REALM.
Response file proxy variables aren't filled and runInstaller fails to execute because of them.

Updates and Proxy usages must be an option and setted like ORACLE_HOME.

Regards, 

-- 
Puppet: 3.8.7
oradb: 2.0.10

**Comment by biemond** [comment]
Hi,

I remember when something is not correct in the rsp it will give you that proxy error.
can you run it yourself, silent install using the rsp and see what needs to be changed.

Thanks

**Comment by biemond** [comment]
So I made a test box https://github.com/biemond/biemond-oradb-vagrant-11.2-ASM-puppet4_3/blob/master/puppet/environments/development/manifests/client.pp

and it working fine for me.

I guess it is some operating system issue or not using the right client install file.

Thanks
