### ISSUE TITLE
12.2 file emocmrsp does not exists

### ISSUE THREAD

**Issue by pmpetit** [biemond/biemond-oradb#153]
Hello,
in module  opatchupgrade.pp
exec { "ksh ${download_dir}/opatch_upgrade_${title}_${opversion}.ksh": 
failed because emocmrsp  does not exists any more.

**Comment by biemond** [comment]
thanks,

Do you have an opatch id with which you upgrade the 12.2 opatch, so I can fix this.

**Comment by biemond** [comment]
fixed , can you check the latest code https://github.com/biemond/biemond-oradb/tree/puppet4_3_data

**Comment by pmpetit** [comment]
it is just during the opatch upgrade (688688)

Envoyé de mon iPhone

**Comment by pmpetit** [comment]
you can try with p6880880_122010_Linux-x86-64.zip

**Comment by pmpetit** [comment]
the opatchupgrade execute
EMOCMRSP=<%= @patchDir %>/ocm/bin/emocmrsp
in the tempalte file ocm.rsp.erb
but in 12.2 version this file emocmrsp does not exist

**Comment by biemond** [comment]
fixed
