### ISSUE TITLE
12.2 : $storage_type and $data_file_destination

### ISSUE THREAD

**Issue by pmpetit** [biemond/biemond-oradb#154]
12.2 
in dbca call : 
-storageType ${storage_type}
is given to dbca,
but in 12.2 , if you set   -storageType FS, then you also have to set -datafileDestination

dbca log extract : 
[INS-04008] Invalid combination of arguments passed from command line. One or more mandatory dependent arguments are not passed for the argument: -storageType

-storageType < FS | ASM >]
			-datafileDestination <Destination directory for all database files>

**Comment by biemond** [comment]
thanks, I will add an check for this.

**Comment by biemond** [comment]
fixed , can you check the latest code https://github.com/biemond/biemond-oradb/tree/puppet4_3_data

**Comment by pmpetit** [comment]
Thanks
