### ISSUE TITLE
Potential compatibility issue with hajee/oracle module

### ISSUE THREAD

**Issue by wfsaxton** [biemond/biemond-oradb#160]
I've successfully created an Oracle 12c (12.2) database using this oradb module on Oracle Linux 7.  When I attempt to create the database along with a user using the hajee/oracle module, the database creation fails (before it even seems to attempt to create the user)

Here is my simple user creation code:
```
ora_user { 'myadmin':
  ensure          => present,
  password        => 'mypasswd',
  grants          => ['SELECT ANY TABLE', 'CONNECT', 'CREATE TABLE', 'CREATE VIEW', 'CREATE TRIGGER'],
}
```

Here is the error:
> Error: Failed to apply catalog: oratab /etc/oratab not found. Probably Oracle not installed

I'm not sure if you have a test case for this.  Let me know if you want a full manifest to try it out with.

**Comment by biemond** [comment]
Hi 
12.2 is doing things differently and have an other oratab default layout which I changed for 12.2
So I guess you need the latest oracle module or report this issue to him 

Thanks

**Comment by wfsaxton** [comment]
Unfortunately, he discontinued the module (I believe in a favor of the one that requires licensing).  Thanks for looking into it.

**Comment by biemond** [comment]
yeah he did, you can now buy a license and get some support
