### ISSUE TITLE
Permission issues with opatch

### ISSUE THREAD

**Issue by sivasamysubramaniam** [biemond/biemond-oradb#173]
Ed, I am still facing the permission issue which was mentioned in earlier issue "Permission issues with opatch  #172 "

I am use opatch as I don't have grid home to use opatch auto..however, I would like to have opatch extract folder as same as patch apply user since root may mess up file permissions and ownership when patch applied through differen user(say oracle install owner)..

can you make that change which Amit mentioned those two lines with puppet.pp.. 

I am currently using oradb 3.0.9 version.

Puppet Code:

#ORACLE DATABASE Patch for Bug# 19285025
oradb::opatch{ "${ora_12102_bugfix_patch_id4}_ldap_patch":
  ensure                    => 'present',
  oracle_product_home       => lookup('ora_12102_home_dir'),
  patch_id                  => "${ora_12102_bugfix_patch_id4}",
  patch_file                => lookup('ora_12102_bugfix_patch_file4'),
  clusterware               => false,
  use_opatchauto_utility    => false,
  user                      => lookup('ora_rdbms_install_user'),
  group                     => lookup('ora_rdbms_install_group'),
  download_dir              => lookup('ora_12102_bugfix_patch_download_dir'),
  ocmrf                     => false,
  puppet_download_mnt_point => lookup('ora_12102_bugfix_patch_download_dir'),
}

Error Message:

Info: opatch_status output 25786014 for patchId 25786014
Notice: /Stage[main]/Profile::Database::Oracle::Ora12102::Linux_ora_12c_database_bugfix/Oradb::Opatch[25921225_sha2_patch]/Exec[extract opatch p25921225_12102170418ProactiveBP_Linux-x86-64.zip 25921225_sha2_patch]/returns: executed successfully
Info: search for patchid 25921225
Info: opatch_status for patch 25921225 command: /appl/oracle/12.1.0.2/OPatch/opatch lsinventory -patch_id -oh /appl/oracle/12.1.0.2 -invPtrLoc /etc/oraInst.loc
Info: opatch_status output NotFound for patchId 25921225
Info: opatch action: present with command /appl/oracle/12.1.0.2/OPatch/opatch apply -silent  -oh /appl/oracle/12.1.0.2 /appl/oracle/software/orardbms12102/bugfixes/25921225
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225â: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/filesâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/files/libâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/files/lib/libcommon12.aâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/files/lib/libcommon12.a/kzsrcr.oâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/files/lib/libcommon12.a/kztv.oâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/files/lib/libserver12.aâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/files/lib/libserver12.a/kzia.oâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/files/lib/libserver12.a/kzal.oâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/README.txtâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/etcâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/etc/configâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/etc/config/inventory.xmlâ: Operation not permitted
chmod: changing permissions of â/appl/oracle/software/orardbms12102/bugfixes/25921225/etc/config/actions.xmlâ: Operation not permitted
Argument(s) Error... Patch location is not valid for apply

Extracted Directory and its permissions:

[root@dg010769 ~]# ls -ld /appl/oracle/software/orardbms12102/bugfixes/25921225
drwxrwxr-x 4 root root 45 Jul  4 20:56 /appl/oracle/software/orardbms12102/bugfixes/25921225
[root@dg010769 ~]#

**Comment by sivasamysubramaniam** [comment]
duplicate

**Comment by biemond** [comment]
yeah I will do the chmod as root and remove it from the command
