### ISSUE TITLE
Puppet5 Warning: Creating ora_asm_diskgroup

### ISSUE THREAD

**Issue by saruvitz-life** [biemond/biemond-oradb#174]
Nice to meet you
I am using Puppet 5, but the following warning is output.
Would you please tell me if there is a way to resolve the warning?
(It may be reproduced also on Puppet 4)

```
Warning: Creating ora_asm_diskgroup via Puppet.newtype is deprecated and will be removed in a future release. Use Puppet::Type.newtype instead.
   (at /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:228:in `newtype')
```

**Comment by biemond** [comment]
yeah,

it is from the oracle module and it used to be free but now only available at puppet enterprise modules. you can contact them or just ignore this warning, I guess it will take some years when they really do it.

my oradb types should be ok.

**Comment by saruvitz-life** [comment]
Thank you for your answer.
