### ISSUE TITLE
allow for SID to be specified in tnsnames.ora creation

### ISSUE THREAD

**Issue by sudodevnull** [biemond/biemond-oradb#191]
Just like the title says.

**Comment by biemond** [comment]
thanks

can you mix service name and sid or is it exclusive. what happens when 1 of those are empty

**Comment by sudodevnull** [comment]
I think it needs to be exclusive though i am not sure.  I have requirements to pass SID=XXX as connection data.

**Comment by biemond** [comment]
yeah add an if on the epp template

**Comment by sudodevnull** [comment]
ok will do.

**Comment by sudodevnull** [comment]
SID is the same thing as Service Name
