### ISSUE TITLE
Opatch versions > 12.2.0.1.9 fail version test

### ISSUE THREAD

**Issue by joechancellor** [biemond/biemond-oradb#195]
https://github.com/biemond/biemond-oradb/blob/4feb20e3fbc13aadaa8df495e489cacf2cf1300e/manifests/opatchupgrade.pp#L87

$opversion values of string '12.2.0.1.10' and string '12.2.0.1.11' are being considered less than '12.2.0.1.5'

12.2.0.1.11 is the October 2017 release of OPatch

**Comment by biemond** [comment]
you are correct

**Comment by biemond** [comment]
fixed. thanks for reporting this.

**Comment by joechancellor** [comment]
Awesome! Thanks!  Love the module.  Your hard work makes my life very easy!
