### ISSUE TITLE
TNS entries when name of entry is different from SERVICE_NAME

### ISSUE THREAD

**Issue by anaelsavioz** [biemond/biemond-oradb#198]
Hello ,

I am using you module to manage my database thanks for your work !

I have a small point, I am not able to manage with your module : TNS entries when the SERVICE_NAME is different from the entry name. 

Example 

```
LAB_DB14 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = DB14.rsvgnw.local)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = LAB)
    )
  )

LAB_DB12 =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = DB12.rsvgnw.local)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = LAB)
    )
  )
```

Currently I am skipping the TNS config on your module and I create the tnsnames.ora file with puppet. Is there a better way to handle that ?

Thanks.
Anaël

**Comment by biemond** [comment]
Hi, 

it should work , title & connect_service_name are not connected.
what is the issue you have and what did you try.

Thanks

**Comment by anaelsavioz** [comment]
Ha okay so it is not limited to one entry "oradb::tnsnames" ....
I thought I had only one entry allowed and all data should be present in "$server" Hash.
I try that right now.

**Comment by anaelsavioz** [comment]
The module is working fine, I didn't understand the documentation.
Have a happy new year !

` oradb::tnsnames {'DUMMY':
    entry_type           => 'tnsnames', 
    oracle_home          => $orahome12,
    user                 => $user,
    group                => $group,
    connect_service_name => 'DUMMY',
    server               => {
      myserver => {    
        host     => $::fqdn,
        port     => 1521,
        protocol => 'TCP'
        }              
      },               
    require              => Db_control['db start'],
  }                    
                       
  oradb::tnsnames {'CAT':
    entry_type           => 'tnsnames',
    oracle_home          => $orahome12,
    user                 => $user,
    group                => $group,
    connect_service_name => 'CATDB',
    server               => {
      myserver => {    
        host     => 'my-cat-db-server.rsvgnw.local',
        port     => 1521,
        protocol => 'TCP'
        }              
      },               
    require              => Db_control['db start'],
  }           `
