### ISSUE TITLE
oracle_exists.rb function returns false if WLS is installed on same machine

### ISSUE THREAD

**Issue by Dhananjay-J-P** [biemond/biemond-oradb#228]
Hey Edwin, Thanks for your efforts. 

I am facing issue when I am trying to install both oracle wls and  oracle database on same machine. oracle_exists.rb function returns false if WLS is installed on same machine, which is causing oracle database to install again. When I checked oradb_inst_products fact I only see /opt/oracle/middleware12c; entry in fact value.

Can you please check?

**Comment by biemond** [comment]
He, 

Can you check you config and make sure both are using the same ora inventory.

this is a bit old but still https://github.com/biemond/biemond-orawls-oradb-vagrant-12.1.3-infra-soa
https://github.com/biemond/biemond-orawls-oradb-vagrant-12.1.3-infra-soa/blob/master/puppet/hieradata/soa.example.com.yaml

for both oracle base is /oracle

**Comment by Dhananjay-J-P** [comment]
Thanks Edwin!!! Issue resolved after matching oraInventory directory for both.
