### ISSUE TITLE
Add swap module as dependency

### ISSUE THREAD

**Issue by ttres** [biemond/biemond-oradb#232]
The [metadata.json](https://github.com/biemond/biemond-oradb/blob/master/metadata.json) does not list the `petems-swap_file` module as a dependency.

**Comment by biemond** [comment]
Hi,  in the oradb code there should not be any dependency to a swap module.  In the examples there are plus in de vagrant boxes it comes with that module.  But it is part of the host provisioning and you can choose what you want.  Maybe the readme should point to that module at the example location.

Thanks

**Comment by ttres** [comment]
Ok, understood.

Sorry for the noise.

**Comment by biemond** [comment]
No problem 

Cheers
