### ISSUE TITLE
tns entries

### ISSUE THREAD

**Issue by chrisdrew1** [biemond/biemond-oradb#236]
Have you thought of having a flag to either have the module overwrite (current behavior) the tnsnames.ora or add to it?

**Comment by biemond** [comment]
Sound good but how will this work in puppet so it won’t keep on adding it

**Comment by chrisdrew1** [comment]
It could be like the sqlnet and a standard file "must contain" type behavior.  We would want a tns for "orcl" but other entries could exist.  Thoughts?

**Comment by biemond** [comment]
ok , I am using https://forge.puppet.com/puppetlabs/concat which does that.

but why not also add these default entries to puppet,  if you want to use them. if not , just remove them less is more.
