### ISSUE TITLE
patch file ownership issue

### ISSUE THREAD

**Issue by chrisdrew1** [biemond/biemond-oradb#247]
Recent RU/PSUs aren't able to apply unless the unzipped directory has the proper group.  I made a fork to address this and it does with with $user and $group set in the extract statement.  The else in this block has the user & group but the initial piece does not.  Can we get this added to the release?
```
case $facts['kernel'] {
    'Linux', 'SunOS': {
      if $ensure == 'present' {
        if $remote_file == true {
          exec { "extract opatch ${patch_file} ${title}":
            command   => "unzip -n ${download_dir}/${patch_file} -d ${download_dir}",
            require   => File["${download_dir}/${patch_file}"],
            creates   => "${download_dir}/${patch_id}",
            path      => $exec_path,
            logoutput => false,
            **_user      => $user,
            group     => $group,_**
            before    => Db_opatch["${patch_id} ${title}"],
          }
        } else {
          exec { "extract opatch ${patch_file} ${title}":
            command   => "unzip -n ${puppet_download_mnt_point}/${patch_file} -d ${download_dir}",
            creates   => "${download_dir}/${patch_id}",
            path      => $exec_path,
            user      => $user,
            group     => $group,
            logoutput => false,
            before    => Db_opatch["${patch_id} ${title}"],
          }
        }
      }
```

**Comment by biemond** [comment]
ok let me check this. do you have a patch number which I can use

**Comment by chrisdrew1** [comment]
Here is my snippet.  July 12.2 RU is 28183653.

oradb::opatch { 'July2018RU_update_28183653':
      ensure                    => present,
      oracle_product_home       => $_oracle_home,
      patch_file                => 'p28183653_122010_Linux-x86-64.zip',
      patch_id                  => '28183653',
      bundle_sub_folder         => '28163133',
      bundle_sub_patch_id       => '28163133',
      clusterware               => false,
      use_opatchauto_utility    => false,
      ocmrf                     => false,
      user                      => 'oracle',
      group                     => 'oinstall',
      download_dir              => $_download_dir,
      puppet_download_mnt_point => $_repo_host_patch,
      require                   => [
        Oradb::Installdb['122_Linux-x86-64'],
        Oradb::Opatchupgrade['p6880880_oradb_opatch_upgrade'],
      ],
    }

**Comment by biemond** [comment]
testing it now with the oct cpu patch for grid with db

**Comment by biemond** [comment]
solved
