### ISSUE TITLE
emConfiguration other than "NONE"

### ISSUE THREAD

**Issue by chrisdrew1** [biemond/biemond-oradb#248]
It looks like in the database.pp there is not option for using "CENTRAL" for the emConfiguration.  Am I missing something?  

There are no omsHost,omsPort, and emUser variables.  Are there plans to add this?

**Comment by biemond** [comment]
not really, if we do this we need to make this work with a rsp file and with a dbt template.
it is more  I need to setup a big environment to test this all. that is why I did not do it plus emagent can also do this or not?

thanks

**Comment by chrisdrew1** [comment]
Ok.  I'll stick with cli scripts to add agents based on facter facts.  Thanks.
