### ISSUE TITLE
puppet variables are camelcase instead of snakecase

### ISSUE THREAD

**Issue by logicminds** [biemond/biemond-oradb#32]
Great module!  Curious why most of the variables do not follow the puppet guidelines and use camel case instead of the snake case guideline?  

II think the difference in this casing is causing problems with rspec puppet as I am not able to test properly when using this module.

**Comment by alexjfisher** [comment]
This ticket's quite old now.  Any plan on fixing this?  I guess it'd be a breaking change, so it's not so straightforward. :(

I found that rspec-puppet *can* still be used, but you have to downcase all your symbol names in the 'with' function.

**Comment by biemond** [comment]
Yeah I know, 

there will be in a few months a new version

Cheers Edwin

**Comment by logicminds** [comment]
Checkout my gem for setting up puppet-rspec tests for you.   https://github.com/logicminds/puppet-retrospec.  Also I wonder if the puppet-lint gem could autofix your Java style?

**Comment by alexjfisher** [comment]
@biemond I feel a bit guilty, but after discussing on IRC, I was asked to open a ticket...
https://tickets.puppetlabs.com/browse/PUP-4752

**Comment by biemond** [comment]
Ok, 

Try to push this week a new version with snake style parameters of all the classes and defines.

**Comment by biemond** [comment]
I pushed a new version with snake style parameters, it works but I need to do some extra testing

**Comment by logicminds** [comment]
@biemond I used my puppet-retrospec gem on your module and produced a lot of new test code.  I also started unit testing the types and found some errors. I'll send some PRs to fix these. Btw, did you use puppet-lint auto fix the Camelcase to snake case?

**Comment by biemond** [comment]
thanks, 

no I did it all manually with the help of sublime text and its great plugins.

**Comment by logicminds** [comment]
We can close this right?
