### ISSUE TITLE
set cwd during asm install

### ISSUE THREAD

**Issue by cliles** [biemond/biemond-oradb#34]
It would be helpful to add cwd to the exec for installasm. The root script and the install script will fail if the site's exec default cwd is / since the grid user does not have correct permissions on /.

I set root.sh to use $gridHome and install orracle grid to $gridBase

This is on sol11.2

I have not made it to installing oracle binaries yet, so this could also be the case there.

**Comment by biemond** [comment]
Ok, in the end we will succeed :-) 

will change it , so probably we should also do this for the normal opatch

**Comment by biemond** [comment]
I changed it for opatch and for opatch auto
