### ISSUE TITLE
Listener, DB creation start/stop create/remove implementation

### ISSUE THREAD

**Issue by carroarmato0** [biemond/biemond-oradb#40]
I have a question regarding the choice of how to define, start/stop Listeners and the creation and deletion of databases.

I notice that you need to first define the relative instance, but then create other resources depending if you want to for example, start a listener, and then use another instance with the stop action to stop one.

Why not add the action in the instance itself? Or use  ensure => 

Example

Current situation:

<pre>
 # tnslsnr Net
  oradb::net{ 'config net8':
    oracleHome   => $ora_home,
    version      => '12.1',
    user         => $ora_user,
    group        => $ora_group,
    downloadDir  => '/install',
    dbPort       => '1521', #optional
  }

  # Listeners
   oradb::listener{'stop listener':
     oracleBase   => $ora_base,
     oracleHome   => $ora_home,
    user         => $ora_user,
     group        => $ora_group,
     action       => 'stop',
     require      => Oradb::Net['config net8'],
   }

  oradb::listener{'start listener':
    oracleBase   => $ora_base,
    oracleHome   => $ora_home,
    user         => $ora_user,
    group        => $ora_group,
    action       => 'start',
   require      => Oradb::Listener['stop listener'],
  }
</pre>

This would make more sense to me:

<pre>
 # with ensure you could define  'running', 'stopped', or 'absent'

 # tnslsnr Net
  oradb::net{ 'config net8':
    oracleHome   => $ora_home,
    version      => '12.1',
    ensure    => 'running',
    user         => $ora_user,
    group        => $ora_group,
    downloadDir  => '/install',
    dbPort       => '1521', #optional
  }
</pre>

**Comment by biemond** [comment]
I think I will make a new manifest, plus add a listener puppet type
and add a warning that oradb::net + listener is deprecated and that they should use the new one.

**Comment by biemond** [comment]
For now I already made db_listener type which also can be used for subscribe/refreshonly. The listener.pp also calls this db_listener type/provider

    db_listener{ 'startlistener':
      ensure          => 'running',  # running|start|abort|stop
      oracle_base_dir => '/oracle',
      oracle_home_dir => '/oracle/product/11.2/db',
      os_user         => 'oracle',
    }

    # subscribe to changes
    db_listener{ 'startlistener':
      ensure          => 'running',  # running|start|abort|stop
      oracle_base_dir => '/oracle',
      oracle_home_dir => '/oracle/product/11.2/db',
      os_user         => 'oracle',
      refreshonly     => true,
      subscribe       => XXXXX,
    }

    # the old way which also calls db_listener type
    oradb::listener{'start listener':
      action       => 'start',  # running|start|abort|stop
      oracleBase   => '/oracle',
      oracleHome   => '/oracle/product/11.2/db',
      user         => 'oracle',
      group        => 'dba',
    }
