### ISSUE TITLE
Oracle Net Services configuration failed on ubuntu 14.04

### ISSUE THREAD

**Issue by trustarun** [biemond/biemond-oradb#41]
I 'am trying to install oracle using oradb on my ubuntu machine(14.04 with 64 bit architecture).
Though Oracle(12.1.0.1) get installed, it fail in the subsequent step i,e
 while running the oradb::net class.

Below is the error log : 

root@tpcloud:/etc/puppet# puppet agent -t
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for tpcloud.puppet.com
Info: Applying configuration version '1420206351'
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns: UnsatisfiedLinkError exception loading native library: njni12
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns: java.lang.UnsatisfiedLinkError: /oracle/product/12.1/db/lib/libnjni12.so: /oracle/product/12.1/db/lib/libclntsh.so.12.1: file too short
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns: java.lang.UnsatisfiedLinkError: oracle.net.common.NetGetEnv.jniGetOracleHome()Ljava/lang/String;
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns:     at oracle.net.common.NetGetEnv.jniGetOracleHome(Native Method)
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns:     at oracle.net.common.NetGetEnv.getOracleHome(Unknown Source)
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns:     at oracle.net.ca.NetCALogger.getOracleHome(NetCALogger.java:230)
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns:     at oracle.net.ca.NetCALogger.initOracleParameters(NetCALogger.java:215)
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns:     at oracle.net.ca.NetCALogger.initLogger(NetCALogger.java:130)
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns:     at oracle.net.ca.NetCA.main(NetCA.java:433)
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns:
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns: Error: oracle.net.common.NetGetEnv.jniGetOracleHome()Ljava/lang/String;
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns: Oracle Net Services configuration failed.  The exit code is 1
Error: netca /silent /responsefile /install/netca_12.1.rsp returned 1 instead of one of [0]
Error: /Stage[main]/Oraclesetup::Oracledb/Oradb::Net[config net8]/Exec[install oracle net config net8]/returns: change from notrun to 0 failed: netca /silent /responsefile /install/netca_12.1.rsp returned 1 instead of one of [0]
Notice: /Stage[main]/Oraclesetup::Oracledb/Oradb::Listener[start listener]/Exec[listener start start listener]: Dependency Exec[install oracle net config net8] has failures: true

I have struggling with it for last 2 weeks but not getting any solution.
Can anyone please help me here .

**Comment by biemond** [comment]
Hi,

I think debian platforms are not supported and I know it works on redhat systems. So probably the installation succeeded but show you some compiler/make warnings and you need to fix all those compiler errors.

And find the ubuntu library replacements for these redhat ones.

    $install = [ 'binutils.x86_64', 'compat-libstdc++-33.x86_64', 'glibc.x86_64','ksh.x86_64','libaio.x86_64',
                'libgcc.x86_64', 'libstdc++.x86_64', 'make.x86_64','compat-libcap1.x86_64', 'gcc.x86_64',
                'gcc-c++.x86_64','glibc-devel.x86_64','libaio-devel.x86_64','libstdc++-devel.x86_64',
                'sysstat.x86_64','unixODBC-devel','glibc.i686','libXext.x86_64','libXtst.x86_64']

    package { $install:
      ensure  => present,
    }

**Comment by trustarun** [comment]
Thanks for your quick reply,

I do have these packages installed. Infact I googled a lot and tried to include all the  packages suggested under different threads.

I also gone through oracle official doc below and make sure that all the packages should be present.

https://docs.oracle.com/database/121/LADBI/pre_install.htm#CIHHCIAB

Below is my current package state:


 $install = [ 'alien', 'autoconf', 'automake', 'autotools-dev', 'binutils', 'doxygen', 'elfutils',
'expat', 'gawk', 'gcc', 'gcc-multilib', 'g++-multilib', 'libstdc++6:i386', 'ksh', 'less','libtiff4-dev',
'lib32z1', 'libaio1', 'libaio-dev', 'libc6-dev', 'libc6-dev-i386', 'libc6-i386', 'libelf-dev', 'libltdl-dev',
'libmotif4','libodbcinstq4-1', 'libodbcinstq4-1:i386', 'libpth-dev', 'libstdc++5', 'lsb-cxx', 'make',
'pdksh', 'openssh-server', 'rlwrap', 'rpm', 'sysstat', 'unixodbc', 'unixodbc-dev', 'x11-utils','zlibc', 'libglapi-mesa:i386', 'libglu1-mesa:i386', 'libqt4-opengl:i386','libpthread-workqueue0', 'libpthread-workqueue-dev', 'libzthread-2.3-2', 'libzthread-dev','libpthread-stubs0-dev', 'unzip' ,'g++', 'libc6', 'libgcc-4.7','libstdc++-4.8-dev', 'libxi-dev', 'libxtst-dev','build-essential']


  package { $install:
    ensure  => present,
  }


All the above package are installed successfully through the puppet script.

I know that there is compiler error at the time of running net config, So assuming that, when I run the script for the first time which installed oracle successfully, but since some dependency package is not available that time, may be subsequent compilation failing, I tried the script on a machine with fresh ubuntu installation.

The script again run successfully, installing all the above package as well as oracle, but again failed at the same point.

The main errors are below:

UnsatisfiedLinkError exception loading native library: njni12
/oracle/product/12.1/db/lib/libnjni12.so: /oracle/product/12.1/db/lib/libclntsh.so.12.1: file too short

infact njni12 error is very common as there is a no of thread related to same issue, but I do not find any fix for ubuntu.

**Comment by SainathNaga** [comment]
Hi,

I am also facing same issue

UnsatisfiedLinkError exception loading native library: njni12
/oracle/product/12.1/db/lib/libnjni12.so: /oracle/product/12.1/db/lib/libclntsh.so.12.1: file too short

Could you please let me know have you find any solution for this.
