### ISSUE TITLE
rootadd_rdbms.sh  rootadd_filemap.sh are not being created 

### ISSUE THREAD

**Issue by leshiynyc** [biemond/biemond-oradb#44]
Hi, 

I keep running into the following error :

Error: Check /orabase/product/11.2.0/4.0/install/root_puppetagent1.vagrant.vm_2015-03-02_11-56-39.log for the output of root script

Error: /Stage[main]/Profile::Oracledb::Install::Install/Oradb::Installdb[11.2.0.4_Linux-x86-64]/Exec[run root.sh script 11.2.0.4_Linux-x86-64]/returns: change from notrun to 0 failed: Check /orabase/product/11.2.0/4.0/install/root_puppetagent1.vagrant.vm_2015-03-02_11-56-39.log for the output of root script

The text below is from the log mentioned in the error above:

Entries will be added to the /etc/oratab file as needed by
Database Configuration Assistant when a database is created
Finished running generic part of root script.
Now product-specific root actions will be performed.
Finished product-specific root actions.
/orabase/product/11.2.0/4.0/root.sh: line 14: /orabase/product/11.2.0/4.0/rdbms/install/rootadd_rdbms.sh: No such file or directory
/orabase/product/11.2.0/4.0/root.sh: line 16: /orabase/product/11.2.0/4.0/rdbms/install/rootadd_filemap.sh: No such file or directory

**Comment by biemond** [comment]
Hi 

Probably the installation failed and somehow it goes to the next step, executing root.sh
Did you install all the required packages, users etc.

And what is the whole output of the installdb, the used configuration or vagrant box, plus check what is there in /orabase/product/11.2.0/4.0

Thanks

**Comment by leshiynyc** [comment]
Hi, 

Thanks for the quick response.You are right, I was not given all the files for the install. Everything is tip-top now !
