### ISSUE TITLE
ASM instance sid for rac vs single instance

### ISSUE THREAD

**Issue by cliles** [biemond/biemond-oradb#45]
When setting the gridType to HA_CONFIG for a single instance ASM database, I get the sid of +ASM for ASM instance.
When setting the gridType to CRS_CONFIG for a RAC database, I get the sid of +ASM1 for ASM instance.

The grid user's bash_profile template should be expanded with a simple conditional for this.

**Comment by biemond** [comment]
Thanks 

Will change this and look at the gridType

**Comment by biemond** [comment]
Done in the latest commit e03bdba67bad6e55de7d0c12f59e99aee41e16c1 of oradb
