### ISSUE TITLE
Install DB from local zip file

### ISSUE THREAD

**Issue by flaviafm** [biemond/biemond-oradb#57]
Hi,

I'm new in puppet so not sure I'm using your module correctly.

But I'm trying to install the Oracle DB in a Centos 6.4 machine (masterless) and when I apply the manifest the first time the it creates file:  db_install_11.2.0.1.rsp and the temp zip file (for instance: linux.x64_11gR2_database_1of2.zip.puppettmp_3786) but it does not create the folder linux.x64_11gR2_database. When I apply the manifest a second time everything works wonder. 

Here the my definition that I'm Using to install DB

`$puppetDownloadMntPoint = "/home/vagrant"`
`$oracleBase    = "/u01/app/oracle/"`
`$oracleHome    = "/u01/app/oracle/product/11.2/db"  `
  
` oradb::installdb{ '112010_Linux-x86-64':`
 `     version       => '11.2.0.1',`
`      file          => 'linux.x64_11gR2_database',`
`      databaseType  => 'EE',`
`      oracleBase    => $oracleBase,`
 `     oracleHome    => $oracleHome,`
`      user          => 'oracle',`
`      group         => 'dba',`
 `     group_install => 'oinstall',`
`      group_oper    => 'oper',`
`      downloadDir   => '/install',`
`     zipExtract    => true,`
`      puppetDownloadMntPoint => $puppetDownloadMntPoint,`
`    }`
}`

Any Idea of why?

Thank you
Flavia

**Comment by biemond** [comment]
Hi,

You can use remote file is false when the zip are already on the vm. This will save memory and need less swap
So you can try that and increase memory and swap plus add the --debug to see all steps

Thanks

**Comment by flaviafm** [comment]
Hallo Edwin ,

Thank you for your quick response. I set the swap and no more issues. Btw, the swap module was updated and for the new version the syntax is

`swap_file::files { 'tmp file swap':`
	`swapfile     => '/var/swap.1',`
		`swapfilesize => '8192000000'`
	`} `

Bedankt,

Flavai
