### ISSUE TITLE
Add oraInventory to client.pp optional parameters

### ISSUE THREAD

**Issue by shoikan** [biemond/biemond-oradb#59]
For a supplier we had to put the orainventory directory one level up from where it is when you install it through your puppet module. Currently it is set somewhere in the code, but by moving it between the () section in client.pp, it is made an optional parameter. As far as I could see it was a 'harmless' modification and helped us out. The diff:

```
[root@someserver environments]# diff {mam,production}/modules/oradb/manifests/client.pp
9d8
<   $oraInventory            = "${oracleBase}/oraInventory",
33a33,34
> 
>   $oraInventory = "${oracleBase}/oraInventory"
```

**Comment by alexjfisher** [comment]
Should be fixed in https://github.com/biemond/biemond-oradb/pull/73
