### ISSUE TITLE
Use Unicode AL32UTF8

### ISSUE THREAD

**Issue by witchbutter** [biemond/biemond-oradb#71]
When using the enterprise edition you are able to choose advanced and then select AL32UTF8 Character Set.  Is there a way to do this with the installdb.pp?  I see there is an option for ee_optional_components, but I have no idea how I would know what those components are.

![oracle10](https://cloud.githubusercontent.com/assets/1911369/10651827/f83f645a-780e-11e5-952d-120a5b4cb39b.jpg)

**Comment by biemond** [comment]
Hi,

what I support is what is possible in the silent response file. in 11g you can define this 
https://github.com/biemond/biemond-oradb/blob/master/templates/db_install_11.2.0.4.rsp.erb#L121
but I don't see these options in 12c, it looks like it installs all and you have to use the right installer.

But for you charset  you can set these on the database manifest.
https://github.com/biemond/biemond-oradb/blob/master/manifests/database.pp#L23

Also it support templates like this so https://github.com/biemond/biemond-oradb/blob/master/templates/dbtemplate_12.1.dbt.erb with this you have total control on how the db looks like.

Hope this helps

**Comment by witchbutter** [comment]
I pulled the option by saving a response file from the gui installer:
			`ee_options_selection      => true,`
			`ee_optional_components    => 'oracle.install.db.config.starterdb.type=GENERAL_PURPOSE:oracle.install.db.config.starterdb.globalDBName=orcl.somedomain.com:oracle.install.db.config.starterdb.SID=orcl:oracle.install.db.ConfigureAsContainerDB=true:oracle.install.db.config.PDBName=pdborcl:oracle.install.db.config.starterdb.characterSet=AL32UTF8:oracle.install.db.config.starterdb.password.ALL=useyourown',`

However there are several other functions I just can't get to work so I am writing my own module in the end anyway.
