### ISSUE TITLE
sqlplus: error while loading shared libraries: libclntsh.so.11.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by weiishann** [biemond/biemond-oradb#74]
Hit the follow error after the installation of the basic DB software 11.2.0.4

Error in the installation logs.

/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status

Have tried setting the LD_LIBRARY_PATH and relinking the library.

Any ideas?

**Comment by biemond** [comment]
yep, that is a library problem 

please do this https://github.com/biemond/biemond-oradb#linux-kernel-ulimits-and-required-packages and use a RedHat family OS. I know ubuntu is not supported.

**Comment by weiishann** [comment]
Thanks for the quick reply. I did set those in the examples. I'm using CentOS7

http://pastebin.com/EhrpK2fp

**Comment by biemond** [comment]
Ok, that explains 11.2.0.4 is not supported on CentOS7, you should use the latest 12.1 version.

**Comment by weiishann** [comment]
I see. I will try it out again. Thanks :)
