### ISSUE TITLE
12.102 Install Issue

### ISSUE THREAD

**Issue by adriennelore** [biemond/biemond-oradb#79]
Hello,

I am not sure if this relates to 12.102 or not, but I was able to successfully get through everything and modify the site.pp file to allow for the minor release, but I get an error.  The actual release file on the Oracle site (I can no longer download 12.101 or I would!)  has an 'se2' in it, which may or may not be relevant.  I successfully get all the way down to the listener starting, but then here is the error message set I get (more notes below the error):

Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: Copying database files
Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: 1% complete
Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: 2% complete
Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: 4% complete
Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: DBCA Operation failed.
Notice: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: Look at the log file "/oracle/cfgtoollogs/dbca/orcl/orcl.log" for further details.
Error: /oracle/product/12.1/db/bin/dbca -silent -responseFile /var/tmp/install/database_oraDb.rsp returned 1 instead of one of [0]
Error: /Stage[main]/Oradb_12c/Oradb::Database[oraDb]/Exec[oracle database oraDb]/returns: change from notrun to 0 failed: /oracle/product/12.1/db/bin/dbca -silent -responseFile /var/tmp/install/database_oraDb.rsp returned 1 instead of one of [0]
Notice: /Stage[main]/Oradb_12c/Oradb::Dbactions[start oraDb]/Db_control[instance control start oraDb]: Dependency Exec[oracle database oraDb] has failures: true
Warning: /Stage[main]/Oradb_12c/Oradb::Dbactions[start oraDb]/Db_control[instance control start oraDb]: Skipping because of failed dependencies
Notice: /Stage[main]/Oradb_12c/Oradb::Autostartdatabase[autostart oracle]/Exec[set dbora soarepos:/oracle/product/12.1/db]: Dependency Exec[oracle database oraDb] has failures: true
Warning: /Stage[main]/Oradb_12c/Oradb::Autostartdatabase[autostart oracle]/Exec[set dbora soarepos:/oracle/product/12.1/db]: Skipping because of failed dependencies

I changed the site.pp file to what is attached!  Thank you so much in advance... I have been working on this for ages and really want to use this image, and if this isn't an 'issue', but something else, if you can point me in the right direction I would appreciate it!

-Adrienne
[site.txt](https://github.com/biemond/biemond-oradb/files/51420/site.txt)

**Comment by biemond** [comment]
Hi ,

can  you take a look at this /oracle/cfgtoollogs/dbca/orcl/orcl.log
the only difference now are the separate download versions for EE and SE. so you must update these parameters

with 12102

For EE 

  file                      => 'linuxamd64_12102_database',
  database_type   => 'EE',

For SE 

  file                      => 'linuxamd64_12102_database_se2',
  database_type   => 'SE',

For 12101 there is only an EE version.

  file                      => 'linuxamd64_12c_database',
  database_type   => 'EE',

**Comment by Mortinke** [comment]
Please look at [#127](https://github.com/biemond/biemond-oradb/issues/127)

For Oracle 12.1.0.2 you could only use 'EE' or 'SE2' for the database_type parameter.   

If this does not work, we need information from the file /oracle/cfgtoollogs/dbca/orcl/orcl.log
