### ISSUE TITLE
/opt/grid/product/11.2.0/gr_1/bin/ocrconfig.bin: error while loading shared libraries: /opt/grid/product/11.2.0/gr_1/lib/libclntsh.so.11.1: file too short

### ISSUE THREAD

**Issue by phil512** [biemond/biemond-oradb#80]
Hello,

I'm trying to deploy a database with ASM and Grid but I keep getting this error : 

/opt/grid/product/11.2.0/gr_1/bin/ocrconfig.bin: error while loading shared libraries: /opt/grid/product/11.2.0/gr_1/lib/libclntsh.so.11.1: file too short

And when I check its size it's 0 byte and there is no symlink pointing to another library 

I'm out of idea, could you please help ? 

Should you need more information, do not hesitate !

Thanks in advance and kind regards
Philippe

**Comment by biemond** [comment]
Hi,

what is the OS with version you tried ( for 11.2 you should redhat family 5 or 6 distribution), use the 11.2.0.4 version plus did you install all the required yum packages. like this.
 
https://github.com/biemond/biemond-oradb-vagrant-11.2-ASM/blob/master/puppet/manifests/site.pp#L68

Thanks

**Comment by phil512** [comment]
Hi and thanks for the fast answer! 

My OS is RHEL 6.6 and I try to deploy 11.2.0.4 

I haven't installed manually those packages. They should be installed automatically if not present or am I wrong? 

I'll give a try right now and let you know what will happen next

**Comment by phil512** [comment]
works perfectly now, thanks again!
