### ISSUE TITLE
database creation 12.1 using dbtemplate_12.1.dbt.erb fails

### ISSUE THREAD

**Issue by dimabarkin** [biemond/biemond-oradb#89]
looks like 12.1 dbca fails on memoryPercentage, recoveryAreaDestination, totalMemory parameters

[main] [ 2016-02-03 08:26:00.864 PST ] [TemplateManager.validateTemplate:633]  Tempalte validation failed with message: cvc-complex-type.2.4.a: Invalid content was found starting w
ith element 'memoryPercentage'. One of '{maxUserConn, percentageMemTOSGA, customSGA, characterSet, nationalCharacterSet, archiveLogMode, initParamFileName, dataVaultEnabled}' is ex
pected.

[main] [ 2016-02-03 08:46:27.865 PST ] [TemplateManager.validateTemplate:633]  Tempalte validation failed with message: cvc-complex-type.2.4.a: Invalid content was found starting w
ith element 'recoveryAreaDestination'. One of '{maxUserConn, percentageMemTOSGA, customSGA, characterSet, nationalCharacterSet, archiveLogMode, initParamFileName, dataVaultEnabled}
' is expected.

[main] [ 2016-02-03 08:50:32.219 PST ] [TemplateManager.validateTemplate:633]  Tempalte validation failed with message: cvc-complex-type.2.4.a: Invalid content was found starting w
ith element 'totalMemory'. One of '{maxUserConn, percentageMemTOSGA, customSGA, characterSet, nationalCharacterSet, archiveLogMode, initParamFileName, dataVaultEnabled}' is expecte
d.

**Comment by biemond** [comment]
Hi,

it should work, you can take a look at https://github.com/biemond/biemond-oradb-vagrant-12.1-CDB/blob/master/puppet/manifests/site.pp#L149

but it is very sensitive for oracle versions and how much memory you assign to the VM, I tested it on 12.1.0.1 with the EE enterprise edition option.
I will also test it on 12.1.0.2 and let you know.

    oradb::database{ 'oraDb':
      oracle_base               => hiera('oracle_base_dir'),
      oracle_home               => hiera('oracle_home_dir'),
      version                   => hiera('dbinstance_version'),
      user                      => hiera('oracle_os_user'),
      group                     => hiera('oracle_os_group'),
      download_dir              => hiera('oracle_download_dir'),
      action                    => 'create',
      db_name                   => hiera('oracle_database_name'),
      db_domain                 => hiera('oracle_database_domain_name'),
      sys_password              => hiera('oracle_database_sys_password'),
      system_password           => hiera('oracle_database_system_password'),
      template                  => 'dbtemplate_12.1',
      character_set             => 'AL32UTF8',
      nationalcharacter_set     => 'UTF8',
      sample_schema             => 'TRUE',
      memory_percentage         => '40',
      memory_total              => '800',
      database_type             => 'MULTIPURPOSE',
      em_configuration          => 'NONE',
      data_file_destination     => hiera('oracle_database_file_dest'),
      recovery_area_destination => hiera('oracle_database_recovery_dest'),
      init_params               => {'open_cursors'        => '1000',
                                    'processes'           => '600',
                                    'job_queue_processes' => '4' },
      container_database        => true,
      require                   => Db_listener['startlistener'],
    }

**Comment by biemond** [comment]
it seems it only worked for 12.1.0.1, I am now changing and testing the template so it also works for 12.1.0.2

**Comment by biemond** [comment]
Got it, 

you can use the latest version from github

Thanks

**Comment by dimabarkin** [comment]
Thanks a lot will test it tonight
Dmitri 

    On Wednesday, February 3, 2016 7:26 PM, Edwin Biemond <notifications@github.com> wrote:
 

 Got it, you can use the latest version from githubThanks—

**Comment by dimabarkin** [comment]
DB creation works. What I've noticed, doesn't matter how I change options in dbtemplate_12.1 oracle dbca always installs all options except sample schemas. Don't think it is oradb module issue. Found several metalink communities articles about similar issues. It is possible to workaround it by providing response  file during db creation, but I don't see that option in oradb module.

Dmitri

**Comment by biemond** [comment]
yep it is , that is because of this https://github.com/biemond/biemond-oradb/blob/master/templates/dbtemplate_12.1.dbt.erb#L17

you can remove the template param from database.pp manifest then it will use the rsp file instead of using a template or we need to replace it with this line

      <option name="SAMPLE_SCHEMA" value="<%= @sample_schema %>"/>

**Comment by dimabarkin** [comment]
Thanks, works
