### ISSUE TITLE
Invalid content was found starting with element 'PROXY_REALM'

### ISSUE THREAD

**Issue by daveseff** [biemond/biemond-oradb#96]
I'm getting the following Error which this puppet module. Not sure if the response file needs to be updated or if I have a different problem. This is on an Amazon AWS instance and I have no swap file. **This is a client install only. **

Starting Oracle Universal Installer...

Checking Temp space: must be greater than 120 MB.   Actual 57316 MB    Passed
Checking swap space: 0 MB available, 150 MB required.    Failed <<<<

>>> Ignoring required pre-requisite failures. Continuing...

Preparing to launch Oracle Universal Installer from /tmp/OraInstall2016-03-24_03-40-05PM. Please wait ...[FATAL] [INS-10105] The given response file /install/db_client_11.2.0.4.rsp is not valid.
   CAUSE: Syntactically incorrect response file. Either unexpected variables are specified or expected variables are not specified in the response file.
   ACTION: Refer the latest product specific response file template
   SUMMARY:
       - cvc-complex-type.2.4.a: Invalid content was found starting with element 'PROXY_REALM'. One of '{"":oracle.install.responseFileVersion, "":oracle.install.client.installType, _**"":SELECTED_LANGUAGES, "":ORACLE_HOSTNAME, "":INVENTORY_LOCATION, "":UNIX_GROUP_NAME, "":ORACLE_BASE, "":ORACLE_HOME, "":oracle.install.client.oramtsPortNumber, "":oracle.install.client.customComponents, "":oracle.install.client.schedulerAgentHostName, "":oracle.install.client.schedulerAgentPortNumber}' is expected.

**Comment by biemond** [comment]
Hi,

maybe it can because of some strange char on the next line of PROXY_REALM in  /install/db_client_11.2.0.4.rsp

else can you run it manually , you can use this rsp plus puppet will show you the install statement,

I will remove the strange char after proxy_realm

Thanks

**Comment by daveseff** [comment]
The .rsp file does not have anything after the PROXY_REALM file. I tried adding a newline at the end but had the same result. 

I get the same result running the installer manually. As a matter of fact, The original error I pasted above was from a manual run.  Here is my db_client_11.2.0.4.rsp:

    ###############################################################################
    ## Copyright(c) Oracle Corporation 1998,2013. All rights reserved.           ##
    ##                                                                           ##
    ## Specify values for the variables listed below to customize                ##
    ## your installation.                                                        ##
    ##                                                                           ##
    ## Each variable is associated with a comment. The comment                   ##
    ## can help to populate the variables with the appropriate                   ##
    ## values.							             ##
    ##                                                                           ##
    ###############################################################################
    
    #-------------------------------------------------------------------------------
    # Do not change the following system generated value.
    #-------------------------------------------------------------------------------
    oracle.install.responseFileVersion=/oracle/install/rspfmt_clientinstall_response_schema_v11_2_0
    
    #-------------------------------------------------------------------------------
    # This variable holds the hostname of the system as set by the user.
    # It can be used to force the installation to use an alternative
    # hostname rather than using the first hostname found on the system
    # (e.g., for systems with multiple hostnames and network interfaces).
    ORACLE_HOSTNAME=
    #-------------------------------------------------------------------------------
    # Unix group to be set for the inventory directory.
    UNIX_GROUP_NAME=oinstall
    #-------------------------------------------------------------------------------
    # Inventory location.
    INVENTORY_LOCATION=/oraInventory
    #-------------------------------------------------------------------------------
    # Specify the languages in which the components will be installed.
    #
    # en   : English                  ja   : Japanese
    # fr   : French                   ko   : Korean
    # ar   : Arabic                   es   : Latin American Spanish
    # bn   : Bengali                  lv   : Latvian
    # pt_BR: Brazilian Portuguese     lt   : Lithuanian
    # bg   : Bulgarian                ms   : Malay
    # fr_CA: Canadian French          es_MX: Mexican Spanish
    # ca   : Catalan                  no   : Norwegian
    # hr   : Croatian                 pl   : Polish
    # cs   : Czech                    pt   : Portuguese
    # da   : Danish                   ro   : Romanian
    # nl   : Dutch                    ru   : Russian
    # ar_EG: Egyptian                 zh_CN: Simplified Chinese
    # en_GB: English (Great Britain)  sk   : Slovak
    # et   : Estonian                 sl   : Slovenian
    # fi   : Finnish                  es_ES: Spanish
    # de   : German                   sv   : Swedish
    # el   : Greek                    th   : Thai
    # iw   : Hebrew                   zh_TW: Traditional Chinese
    # hu   : Hungarian                tr   : Turkish
    # is   : Icelandic                uk   : Ukrainian
    # in   : Indonesian               vi   : Vietnamese
    # it   : Italian
    #
    # all_langs   : All languages
    #
    # Specify value as the following to select any of the languages.
    # Example : SELECTED_LANGUAGES=en,fr,ja
    #
    # Specify value as the following to select all the languages.
    # Example : SELECTED_LANGUAGES=all_langs
    #-------------------------------------------------------------------------------
    SELECTED_LANGUAGES=en
    #-------------------------------------------------------------------------------
    # Complete path of the Oracle Home
    ORACLE_HOME=/apps/oracle/product/11.1/client
    #-------------------------------------------------------------------------------
    # Complete path of the Oracle Base.
    ORACLE_BASE=/apps/oracle
    #-------------------------------------------------------------------------------
    #Name       : INSTALL_TYPE
    #Datatype   : String
    #Description: Installation type of the component.
    #
    #             The following choices are available. The value should contain
    #             only one of these choices.
    #               - InstantClient
    #               - Administrator
    #               - Runtime
    #               - Custom
    #
    #Example    : INSTALL_TYPE = "Administrator"
    #------------------------------------------------------------------------------
    oracle.install.client.installType=Administrator
    #-------------------------------------------------------------------------------
    #Name       : oracle.install.client.upgrading
    #Datatype   : boolean
    #Description: whether or not this is an upgrade installation
    #
    #             The following choices are available. The value should contain
    #             only one of these choices.
    #               - true
    #               - false
    #
    #Example    : oracle.install.client.upgrading=true
    #------------------------------------------------------------------------------
    oracle.install.client.upgrading=
    #------------------------------------------------------------------------------
    # Name       : oracle.install.client.customComponents
    # Datatype   : StringList
    #
    # This property is considered only if INSTALL_TYPE is set to "Custom"
    #
    # Description: List of Client Components you would like to install
    #
    #   The following choices are available. You may specify any
    #   combination of these choices.  The components you choose should
    #   be specified in the form "internal-component-name:version"
    #   Below is a list of components you may specify to install.
    #
    # oracle.sqlj:11.2.0.4.0 -- "Oracle SQLJ"
    # oracle.rdbms.util:11.2.0.4.0 -- "Oracle Database Utilities"
    # oracle.javavm.client:11.2.0.4.0 -- "Oracle Java Client"
    # oracle.sqlplus:11.2.0.4.0 -- "SQL*Plus"
    # oracle.dbjava.jdbc:11.2.0.4.0 -- "Oracle JDBC/THIN Interfaces"
    # oracle.ldap.client:11.2.0.4.0 -- "Oracle Internet Directory Client"
    # oracle.rdbms.oci:11.2.0.4.0 -- "Oracle Call Interface (OCI)"
    # oracle.precomp:11.2.0.4.0 -- "Oracle Programmer"
    # oracle.xdk:11.2.0.4.0 -- "Oracle XML Development Kit"
    # oracle.network.aso:11.2.0.4.0 -- "Oracle Advanced Security"
    # oracle.assistants.oemlt:11.2.0.4.0 -- "Enterprise Manager Minimal Integration"
    # oracle.oraolap.mgmt:11.2.0.4.0 -- "OLAP Analytic Workspace Manager and Worksheet"
    # oracle.network.client:11.2.0.4.0 -- "Oracle Net"
    # oracle.network.cman:11.2.0.4.0 -- "Oracle Connection Manager"
    # oracle.network.listener:11.2.0.4.0 -- "Oracle Net Listener"
    # oracle.ordim.client:11.2.0.4.0 -- "Oracle Multimedia Client Option"
    # oracle.odbc:11.2.0.4.0 -- "Oracle ODBC Driver"
    # oracle.has.client:11.2.0.4.0 -- "Oracle Clusterware High Availability API"
    # oracle.dbdev:11.2.0.4.0 -- "Oracle SQL Developer"
    # oracle.rdbms.scheduler:11.2.0.4.0 -- "Oracle Scheduler Agent"
    #
    #-------------------------------------------------------------------------------
    oracle.install.client.customComponents="oracle.sqlj:11.2.0.4.0","oracle.rdbms.util:11.2.0.4.0","oracle.javavm.client:11.2.0.4.0","oracle.sqlplus:11.2.0.4.0","oracle.dbjava.jdbc:11.2.0.4.0","oracle.ldap.client:11.2.0.4.0","oracle.rdbms.oci:11.2.0.4.0","oracle.precomp:11.2.0.4.0","oracle.xdk:11.2.0.4.0","oracle.network.aso:11.2.0.4.0","oracle.assistants.oemlt:11.2.0.4.0","oracle.oraolap.mgmt:11.2.0.4.0","oracle.network.client:11.2.0.4.0","oracle.network.cman:11.2.0.4.0","oracle.network.listener:11.2.0.4.0","oracle.ordim.client:11.2.0.4.0","oracle.odbc:11.2.0.4.0","oracle.has.client:11.2.0.4.0","oracle.dbdev:11.2.0.4.0","oracle.rdbms.scheduler:11.2.0.4.0"
    #-------------------------------------------------------------------------------
    # Host name to be used for by the Oracle Scheduler Agent.
    # This needs to be entered in case oracle.rdbms.scheduler is selected in the
    # list of custom components during custom install
    #
    # Example    : oracle.install.client.schedulerAgentHostName = acme.domain.com
    #------------------------------------------------------------------------------
    oracle.install.client.schedulerAgentHostName=
    
    #------------------------------------------------------------------------------
    # Port number to be used for by the Oracle Scheduler Agent.
    # This needs to be entered in case oracle.rdbms.scheduler is selected in the
    # list of custom components during custom install
    #
    # Example: oracle.install.client.schedulerAgentPortNumber = 1500
    #------------------------------------------------------------------------------
    oracle.install.client.schedulerAgentPortNumber=
    #------------------------------------------------------------------------------
    # Specify the auto-updates option. It can be one of the following:
    #   - MYORACLESUPPORT_DOWNLOAD
    #   - OFFLINE_UPDATES
    #   - SKIP_UPDATES
    #------------------------------------------------------------------------------
    oracle.installer.autoupdates.option=
    
    #------------------------------------------------------------------------------
    # In case MYORACLESUPPORT_DOWNLOAD option is chosen, specify the location where
    # the updates are to be downloaded.
    # In case OFFLINE_UPDATES option is chosen, specify the location where the updates
    # are present.
    #------------------------------------------------------------------------------
    oracle.installer.autoupdates.downloadUpdatesLoc=
    
    #------------------------------------------------------------------------------
    # Specify the My Oracle Support Account Username which has the patches download privileges
    # to be used for software updates.
    #
    #  Example   : AUTOUPDATES_MYORACLESUPPORT_USERNAME=abc@oracle.com
    #------------------------------------------------------------------------------
    AUTOUPDATES_MYORACLESUPPORT_USERNAME=
    #------------------------------------------------------------------------------
    # Specify the My Oracle Support Account Username password which has the patches download privileges
    # to be used for software updates.
    #
    # Example    : AUTOUPDATES_MYORACLESUPPORT_PASSWORD=password
    #------------------------------------------------------------------------------
    AUTOUPDATES_MYORACLESUPPORT_PASSWORD=
    
    #------------------------------------------------------------------------------
    # Specify the Proxy server name. Length should be greater than zero.
    #
    # Example    : PROXY_HOST=proxy.domain.com
    #------------------------------------------------------------------------------
    PROXY_HOST=
    
    #------------------------------------------------------------------------------
    # Specify the proxy port number. Should be Numeric and at least 2 chars.
    #
    # Example    : PROXY_PORT=25
    #------------------------------------------------------------------------------
    PROXY_PORT=
    #------------------------------------------------------------------------------
    # Specify the proxy user name. Leave PROXY_USER and PROXY_PWD
    # blank if your proxy server requires no authentication.
    #
    # Example    : PROXY_USER=username
    #------------------------------------------------------------------------------
    PROXY_USER=
    #------------------------------------------------------------------------------
    # Specify the proxy password. Leave PROXY_USER and PROXY_PWD
    # blank if your proxy server requires no authentication.
    #
    # Example    : PROXY_PWD=password
    #------------------------------------------------------------------------------
    PROXY_PWD=
    
    #------------------------------------------------------------------------------
    # Specify the proxy realm.
    #
    # Example    : PROXY_REALM=metalink
    #------------------------------------------------------------------------------
    PROXY_REALM=

**Comment by biemond** [comment]
Hi,

it looks ok , but can you change this 
INVENTORY_LOCATION=/oraInventory
to 
INVENTORY_LOCATION=/app/oracle/oraInventory

Else you need root permission to create this folder.

**Comment by daveseff** [comment]
Cool. Yes I had moved the inventory like you suggested, although puppet seems to create it just fine. 

I ran the client manually with a gui to record a new rsp file. I changed my template as such ( I've stripped out the comments for brevity). It seems to not whinge about the Proxy settings anymore but fails because it can not find the root.sh file

    oracle.install.responseFileVersion=/oracle/install/rspfmt_clientinstall_response_schema_v11_2_0
    ORACLE_HOSTNAME=<%= @hostname %>
    UNIX_GROUP_NAME=<%= @group_install %>
    INVENTORY_LOCATION=<%= @oraInventory %>
    SELECTED_LANGUAGES=en
    ORACLE_HOME=<%= @oracle_home %>
    ORACLE_BASE=<%= @oracle_base %>
    oracle.install.client.installType=InstantClient
    oracle.install.client.customComponents=
    oracle.install.client.oramtsPortNumber=
    oracle.install.client.schedulerAgentHostName=


New Error:

    Error: Could not find command '/apps/oracle/product/11.1/client/root.sh'
    Error: /Stage[main]/Profiles::Oracle::Client/Oradb::Client[11.2.0.4_Linux-x86-64]/Exec[run root.sh 
    script 11.2.0.4_Linux-x86-64]/returns: change from notrun to 0 failed: Could not find command 
    '/apps/oracle/product/11.1/client/root.sh'

**Comment by phil512** [comment]
Hello,

This issue has not been fixed ?

I have exactly the same error with puppet : 

[...]
Notice: /Stage[main]/Oracle11client/Oradb::Client[11.2.0.4_Linux-x86-64]/Exec[install oracle client 11.2.0.4_Linux-x86-64]/returns:        - cvc-complex-type.2.4.a: Invalid content was found starting with element 'PROXY_REALM'. One of '{"":oracle.install.responseFileVersion, "":oracle.install.client.installType, "":SELECTED_LANGUAGES, "":ORACLE_HOSTNAME, "":INVENTORY_LOCATION, "":UNIX_GROUP_NAME, "":ORACLE_BASE, "":ORACLE_HOME, "":oracle.install.client.oramtsPortNumber, "":oracle.install.client.customComponents, "":oracle.install.client.schedulerAgentHostName, "":oracle.install.client.schedulerAgentPortNumber}' is expected.

Do you have any update regarding this issue ? how can we install automatically the oracle client without manual action ?

Thanks in advance,
Philippe

**Comment by biemond** [comment]
I think it was an invalid value for INVENTORY_LOCATION. 

does it work when you remove these proxy entries
https://github.com/biemond/biemond-oradb/blob/master/templates/db_client_11.2.0.4.rsp.erb#L217

thanks

**Comment by phil512** [comment]
Hello,

No it's not working better : 

Notice: /Stage[main]/Oracle11client/Oradb::Client[11.2.0.4_Linux-x86-64]/Exec[install oracle client 11.2.0.4_Linux-x86-64]/returns:    CAUSE: Syntactically incorrect response file. Either unexpected variables are specified or expected variables are not specified in the response file.
Notice: /Stage[main]/Oracle11client/Oradb::Client[11.2.0.4_Linux-x86-64]/Exec[install oracle client 11.2.0.4_Linux-x86-64]/returns:    ACTION: Refer the latest product specific response file template
Notice: /Stage[main]/Oracle11client/Oradb::Client[11.2.0.4_Linux-x86-64]/Exec[install oracle client 11.2.0.4_Linux-x86-64]/returns:    SUMMARY:
Notice: /Stage[main]/Oracle11client/Oradb::Client[11.2.0.4_Linux-x86-64]/Exec[install oracle client 11.2.0.4_Linux-x86-64]/returns:        - cvc-complex-type.2.4.a: Invalid content was found starting with element 'AUTOUPDATES_MYORACLESUPPORT_PASSWORD'. One of '{"":oracle.install.responseFileVersion, "":oracle.install.client.installType, "":SELECTED_LANGUAGES, "":ORACLE_HOSTNAME, "":INVENTORY_LOCATION, "":UNIX_GROUP_NAME, "":ORACLE_BASE, "":ORACLE_HOME, "":oracle.install.client.oramtsPortNumber, "":oracle.install.client.customComponents, "":oracle.install.client.schedulerAgentHostName, "":oracle.install.client.schedulerAgentPortNumber}' is expected.


I have deleted all proxy entres at the end of the file and it's not working better

Philippe

**Comment by biemond** [comment]
Yeah so strange.

are you using this file 11g client file from Oracle support

      version               => '11.2.0.4',
      file                      => 'p13390677_112040_Linux-x86-64_4of7.zip',

because the one from OTN is version 11.2.0.1 and this uses a different RSP file.

else we need to make a rsp file from OUI and save this rsp in the last step of the installer. Then we can compare it or use it.

thanks

**Comment by phil512** [comment]
No I was using the binary that our DBA gave to me 

I will now give a try with this file once downloaded from the Oracle support and let you know how it works then
Thanks

**Comment by phil512** [comment]
with this binary the installation was successful on first try, so that was the issue

Thanks again!

**Comment by biemond** [comment]
Cool,

Probably you had to specify version is 11.2.0.1 for your first binary 

Thanks
